### ISSUE TITLE
Selected radio buttons are illegible

### ISSUE THREAD

**Issue by EliTheCoder** [joelongstreet/data-forms#7]
Selected radio buttons appear white which is the same color as the text on top of them.
![image](https://user-images.githubusercontent.com/4386738/57199606-bcf3d100-6f46-11e9-9cfc-5f1aa4c28859.png)
![image](https://user-images.githubusercontent.com/4386738/57199610-c846fc80-6f46-11e9-8a2d-6712735bb40a.png)
![image](https://user-images.githubusercontent.com/4386738/57199613-cf6e0a80-6f46-11e9-8608-62c5555bbebe.png)

**Comment by joelongstreet** [comment]
Pull the latest and you should see it fixed. Let me know if you're still seeing otherwise.

<img width="166" alt="Screen Shot 2019-05-05 at 21 34 59" src="https://user-images.githubusercontent.com/260920/57204477-b3399000-6f7d-11e9-82c9-a5638a90fc8f.png">

Long time no talk. What's new?

**Comment by EliTheCoder** [comment]
I'm still getting the same issue even after pulling the latest changes. Luckily, I can just use https://joelongstreet.com/data-forms. Feel free to leave this issue closed.

I feel that I've improved a lot on my programming since the last time we met. I've learned a lot of new languages (TypeScript, Python, Java, C, C++, Less, [Rockstar](https://github.com/RockstarLang/rockstar), a bit of Ruby, a bit of Rust, a bit of [Julia](https://julialang.org), a bit of [Haskell](https://haskell.org)). My main languages are JavaScript and TypeScript. I really like doing backend stuff with NodeJS. I also like making cool animations and projects using [P5.js](https://p5js.org). P5.js is like Processing for JavaScript. A few of my favorite P5.js projects are these: 
- https://editor.p5js.org/EliTheCoder/present/OchJAimmx
- https://editor.p5js.org/EliTheCoder/present/KYZbMZXob
- https://editor.p5js.org/EliTheCoder/present/1doPnUSJl

I've done a lot of multiplayer web apps too. I use socket.io, NodeJS, HTML, Less, and TypeScript. I also have made a lot of bots for [Discord](https://discordapp.com) (pretty much Slack for gamers). My current IDE is VSCode. That's about everything that's new. Feel free to [email me](mailto:ex.games.org@gmail.com) if you wanna chat. :)
